import numpy as np
import pandas as pd

from cluster_structures import *
from scoring_utils import *

sys.path.insert(1,'/home/STEGG_controler/post_processing/')
from energy_min import *

def get_ape_gen_diverse(directory_path, log_filepath, num_top_conformations=3):
    """
    Identifies the best diverse set of conformations generated by Ape-GEN 2.0
    by combining clustering information with affinity scores.

    Args:
        directory_path (str): Path to the directory containing PDB files of
                              Ape-GEN conformations.
        log_filepath (str): Path to the Ape-GEN 2.0 output log file
                            (used to extract affinity scores).
        num_top_conformations (int): The number of top diverse conformations to return.
                                     Defaults to 10.

    Returns:
        pandas.DataFrame: A DataFrame containing information (Peptide_Index, Affinity,
                          cluster num) for the selected best diverse conformations.
    """
    # Perform clustering on the conformations to group similar structures
    # Using 'all' atoms, 15 PCA components, and 15 clusters as defaults.

    # if fewer than 15 conformations, just return the ones we have for now
    n_c = len([f for f in os.listdir(directory_path) if f.endswith('.pdb')])
    if nc == 0:
        print('Zero conformations generated by APE-Gen 2.0')
        raise
    if nc <= 15:
        print('Very few conformations generated by APE-Gen 2.0')
        return None

    structure_clusters = cluster_main(directory_path, atom_type='all', pca_components=15, n_clusters=15)

    # Get affinity scores from the Ape-GEN log file
    affinity_scores_df = get_ape_gen_scores(log_filepath)

    # Convert 'Peptide_Index' in the affinity DataFrame to match the PDB filenames
    # (e.g., '0001' becomes 'pMHC_0001.pdb')
    affinity_scores_df['Peptide_Index'] = affinity_scores_df['Peptide_Index'].apply(lambda x: f'pMHC_{x}.pdb')

    # Convert the cluster dictionary to a DataFrame for merging
    clusters_df = pd.DataFrame(list(structure_clusters.items()), columns=['Peptide_Index', 'cluster_number'])

    # Merge the affinity scores with the cluster assignments based on 'Peptide_Index'
    merged_data_df = pd.merge(affinity_scores_df, clusters_df, on='Peptide_Index', how='left')

    # Sort the merged DataFrame by 'Affinity' in ascending order (lower affinity is better)
    sorted_by_affinity_df = merged_data_df.sort_values(by='Affinity')

    # Select one conformation from each unique cluster, prioritizing those with better affinity
    diverse_conformations_df = sorted_by_affinity_df.drop_duplicates(subset='cluster_number')

    # Select the top 'num_top_conformations' from this diverse set
    top_diverse_set_df = diverse_conformations_df.head(num_top_conformations)

    return top_diverse_set_df


def get_t_recs_diverse(directory_path, num_top_conformations=25):
    """
    Identifies the best diverse set of TCR conformations generated by T-RECS.
    We use energy based selection here, as T-RECS does not directly provide
    affinity scores like Ape-GEN.

    Args:
        directory_path (str): Path to the directory containing PDB files of
                              T-RECS conformations.
        num_top_conformations (int, optional): The number of top diverse conformations to return.
                                               Currently unused for selection.

    Returns:
        A DataFrame containing information
    """
    # Perform clustering on the TCR conformations
    # Using 'all' atoms, 35 PCA components, and 35 clusters as defaults.
    # These parameters might need tuning based on the dataset.
    structure_clusters = cluster_main(directory_path, atom_type='all', pca_components=35, n_clusters=35)

    # Convert the cluster dictionary to a DataFrame for merging
    clusters_df = pd.DataFrame(list(structure_clusters.items()), columns=['tcr_pdb_name', 'cluster_number'])
    clusters_df['energy_vals'] = None

    # minimize structures and get scores
    for i,row in clusters_df.iterrows():
        clusters_df.at[i,'energy_vals'] = minimizeConf(directory_path+'/'+row['tcr_pdb_name'])
        clusters_df.at[i,'tcr_pdb_name'] = row['tcr_pdb_name'][:-4]+'_minimized.pdb'

    # Sort the merged DataFrame by 'Affinity' in ascending order (lower affinity is better)
    sorted_by_energy_df = clusters_df.sort_values(by='energy_vals')

    # Select one conformation from each unique cluster, prioritizing those with better affinity
    diverse_conformations_df = sorted_by_energy_df.drop_duplicates(subset='cluster_number')

    # Select the top 'num_top_conformations' from this diverse set
    top_diverse_set_df = diverse_conformations_df.head(num_top_conformations)

    print('top diverse set: ',top_diverse_set_df)

    return top_diverse_set_df